name               = "haya-api"
compatibility_date = "2025-05-06"
workers_dev        = true

# Topâ€level flag to enable Node builtins at runtime
compatibility_flags = ["nodejs_compat"]

# Point to our Worker wrapper
main               = "worker.js"

[build]
  command = "npm ci"
